In [6]:
from wwo_hist import retrieve_hist_data
import glob
import pandas as pd
import os

In [2]:
os.chdir("Documents/GitHub/PV-Module-Model/")

In [11]:
"""
frequency = 24
start_date = '21-JAN-2011'
end_date = '4-MAR-2012'
api_key = '8918d442e14940ae9fa04448201507'
location_list = ['32922']

hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)
"""

Retrieving weather data for 32922


Currently retrieving data for 32922: from 2011-01-21 to 2011-01-31
Time elapsed (hh:mm:ss.ms) 0:00:00.811916
Currently retrieving data for 32922: from 2011-02-01 to 2011-02-28
Time elapsed (hh:mm:ss.ms) 0:00:01.311465
Currently retrieving data for 32922: from 2011-03-01 to 2011-03-31
Time elapsed (hh:mm:ss.ms) 0:00:02.782153
Currently retrieving data for 32922: from 2011-04-01 to 2011-04-30
Time elapsed (hh:mm:ss.ms) 0:00:03.332337
Currently retrieving data for 32922: from 2011-05-01 to 2011-05-31
Time elapsed (hh:mm:ss.ms) 0:00:03.881223
Currently retrieving data for 32922: from 2011-06-01 to 2011-06-30
Time elapsed (hh:mm:ss.ms) 0:00:05.076035
Currently retrieving data for 32922: from 2011-07-01 to 2011-07-31
Time elapsed (hh:mm:ss.ms) 0:00:05.609861
Currently retrieving data for 32922: from 2011-08-01 to 2011-08-31
Time elapsed (hh:mm:ss.ms) 0:00:07.021678
Currently retrieving data for 32922: from 2011-09-01 to 2011-09-30
Time elapsed (hh:mm:ss.ms) 0:00:07.536892
Currently retrieving data for 32922: from 2011-10-01 to 2011-10-31
Time elapsed (hh:mm:ss.ms) 0:00:08.989388
Currently retrieving data for 32922: from 2011-11-01 to 2011-11-30
Time elapsed (hh:mm:ss.ms) 0:00:10.205865
Currently retrieving data for 32922: from 2011-12-01 to 2011-12-31
Time elapsed (hh:mm:ss.ms) 0:00:10.773050
Currently retrieving data for 32922: from 2012-01-01 to 2012-01-31
Time elapsed (hh:mm:ss.ms) 0:00:11.543652
Currently retrieving data for 32922: from 2012-02-01 to 2012-02-29
Time elapsed (hh:mm:ss.ms) 0:00:12.110916
Currently retrieving data for 32922: from 2012-03-01 to 2012-03-04
Time elapsed (hh:mm:ss.ms) 0:00:12.610161


export 32922 completed!

In [12]:
"""
frequency = 24
start_date = '14-AUG-2013'
end_date = '24-SEP-2014'
api_key = '8918d442e14940ae9fa04448201507'
location_list = ['97401']

hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)
"""

Retrieving weather data for 97401


Currently retrieving data for 97401: from 2013-08-14 to 2013-08-31
Time elapsed (hh:mm:ss.ms) 0:00:00.372620
Currently retrieving data for 97401: from 2013-09-01 to 2013-09-30
Time elapsed (hh:mm:ss.ms) 0:00:00.926763
Currently retrieving data for 97401: from 2013-10-01 to 2013-10-31
Time elapsed (hh:mm:ss.ms) 0:00:01.502469
Currently retrieving data for 97401: from 2013-11-01 to 2013-11-30
Time elapsed (hh:mm:ss.ms) 0:00:02.068600
Currently retrieving data for 97401: from 2013-12-01 to 2013-12-31
Time elapsed (hh:mm:ss.ms) 0:00:03.274720
Currently retrieving data for 97401: from 2014-01-01 to 2014-01-31
Time elapsed (hh:mm:ss.ms) 0:00:03.855192
Currently retrieving data for 97401: from 2014-02-01 to 2014-02-28
Time elapsed (hh:mm:ss.ms) 0:00:04.914008
Currently retrieving data for 97401: from 2014-03-01 to 2014-03-31
Time elapsed (hh:mm:ss.ms) 0:00:05.990304
Currently retrieving data for 97401: from 2014-04-01 to 2014-04-30
Time elapsed (hh:mm:ss.ms) 0:00:07.078862
Currently retrieving data for 97401: from 2014-05-01 to 2014-05-31
Time elapsed (hh:mm:ss.ms) 0:00:07.613609
Currently retrieving data for 97401: from 2014-06-01 to 2014-06-30
Time elapsed (hh:mm:ss.ms) 0:00:08.833294
Currently retrieving data for 97401: from 2014-07-01 to 2014-07-31
Time elapsed (hh:mm:ss.ms) 0:00:09.993884
Currently retrieving data for 97401: from 2014-08-01 to 2014-08-31
Time elapsed (hh:mm:ss.ms) 0:00:11.224784
Currently retrieving data for 97401: from 2014-09-01 to 2014-09-24
Time elapsed (hh:mm:ss.ms) 0:00:12.230777


export 97401 completed!

In [13]:
"""
frequency = 24
start_date = '20-DEC-2012'
end_date = '20-JAN-2014'
api_key = '8918d442e14940ae9fa04448201507'
location_list = ['80401']

hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)
"""

Retrieving weather data for 80401


Currently retrieving data for 80401: from 2012-12-20 to 2012-12-31
Time elapsed (hh:mm:ss.ms) 0:00:00.861028
Currently retrieving data for 80401: from 2013-01-01 to 2013-01-31
Time elapsed (hh:mm:ss.ms) 0:00:03.097722
Currently retrieving data for 80401: from 2013-02-01 to 2013-02-28
Time elapsed (hh:mm:ss.ms) 0:00:04.336008
Currently retrieving data for 80401: from 2013-03-01 to 2013-03-31
Time elapsed (hh:mm:ss.ms) 0:00:05.937198
Currently retrieving data for 80401: from 2013-04-01 to 2013-04-30
Time elapsed (hh:mm:ss.ms) 0:00:06.991267
Currently retrieving data for 80401: from 2013-05-01 to 2013-05-31
Time elapsed (hh:mm:ss.ms) 0:00:08.197205
Currently retrieving data for 80401: from 2013-06-01 to 2013-06-30
Time elapsed (hh:mm:ss.ms) 0:00:09.494197
Currently retrieving data for 80401: from 2013-07-01 to 2013-07-31
Time elapsed (hh:mm:ss.ms) 0:00:10.643957
Currently retrieving data for 80401: from 2013-08-01 to 2013-08-31
Time elapsed (hh:mm:ss.ms) 0:00:11.888952
Currently retrieving data for 80401: from 2013-09-01 to 2013-09-30
Time elapsed (hh:mm:ss.ms) 0:00:12.967838
Currently retrieving data for 80401: from 2013-10-01 to 2013-10-31
Time elapsed (hh:mm:ss.ms) 0:00:14.548017
Currently retrieving data for 80401: from 2013-11-01 to 2013-11-30
Time elapsed (hh:mm:ss.ms) 0:00:15.605993
Currently retrieving data for 80401: from 2013-12-01 to 2013-12-31
Time elapsed (hh:mm:ss.ms) 0:00:16.747189
Currently retrieving data for 80401: from 2014-01-01 to 2014-01-20
Time elapsed (hh:mm:ss.ms) 0:00:17.748019


export 80401 completed!

In [14]:
"""
files = ["/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/cocoa.csv", 
         "/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/golden.csv",  
         "/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/eugene.csv"]
"""

['/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/cocoa.csv', '/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/golden.csv', '/Users/edwardxiong/Documents/GitHub/PV-Module-Model/weather-data/eugene.csv']

In [15]:
"""dfs = []
for file in files:
    dfs.append(pd.read_csv(file))
df = pd.concat(dfs)
df.to_csv("weather-data.csv")
"""

In [20]:
df = pd.read_csv("weather-data.csv")
df

,Unnamed: 0,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,0,2011-01-21,20,17,0.0,5.2,4,84,09:11 PM,09:21 AM,...,21,70,91,6.0,1010,20,10,176,14,32922
1,1,2011-01-22,16,9,0.0,10.4,4,77,10:17 PM,10:00 AM,...,28,38,75,0.2,1011,16,10,299,21,32922
2,2,2011-01-23,15,6,0.0,10.4,4,69,11:23 PM,10:37 AM,...,21,8,67,0.0,1020,15,10,221,14,32922
3,3,2011-01-24,20,13,0.0,8.4,4,62,No moonrise,11:16 AM,...,22,44,74,0.6,1022,20,10,99,14,32922
4,4,2011-01-25,23,18,0.0,5.2,5,55,12:27 AM,11:55 AM,...,38,71,83,3.4,1016,23,10,158,23,32922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,402,2014-09-20,35,12,0.0,11.6,6,11,03:36 AM,05:24 PM,...,11,0,63,0.0,1013,35,10,156,6,97401
1209,403,2014-09-21,28,11,0.0,11.6,5,3,04:33 AM,05:53 PM,...,8,15,75,0.0,1013,28,8,255,5,97401
1210,404,2014-09-22,24,11,0.0,10.2,5,0,05:32 AM,06:21 PM,...,7,68,81,0.0,1015,24,6,244,5,97401
1211,405,2014-09-23,25,12,0.0,10.2,5,0,06:30 AM,06:48 PM,...,9,57,81,0.0,1010,25,9,193,5,97401
1212,406,2014-09-24,16,12,0.0,6.0,3,0,07:30 AM,07:17 PM,...,8,97,97,9.3,1011,16,3,158,5,97401